### ISSUE TITLE
Solder the LED driver and the MPU6050

### ISSUE THREAD

**Issue by tb2459** [tb2459/FlexMania#10]
- [x] Solder the new part(s) accordingly

**Comment by tb2459** [comment]
We have soldered our board and now we will be testing our connections.

**Comment by tb2459** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/87879969/220708559-ff3e7e3d-ecd1-4094-b443-f38b98ce455c.png">

**Comment by Bkon243** [comment]
![Soldered MPU 6050](https://user-images.githubusercontent.com/98844170/220710261-1384f99c-925b-479c-a9f9-28c6039f6101.jpg)
