### ISSUE TITLE
Implement User Interface 

### ISSUE THREAD

**Issue by tb2459** [tb2459/FlexMania#27]
- [x] Have personas 
- [x] Have a wireframe and sketch

**Comment by tb2459** [comment]
We have gathered 5 personas for our personas and also created a wireframe presentation for our design.

**Comment by tb2459** [comment]
@ffund we shared our wireframe presentation named "FlexMania Wireframe" through your email and were wondering if you could check that out to give us some feedback. Thank you!

**Comment by ffund** [comment]
@tb2459 can you also share the personas (and the user research + affinity map) used to create them? I will review wireframes with the personas in mind. (i.e. do the plans for the UX satisfy what the personas will want and expect.)
