### ISSUE TITLE
Set up repository on Github

### ISSUE THREAD

**Issue by tb2459** [tb2459/FlexMania#8]
- [x] Create Repository 
- [x] Add Collaborators 
- [x] Set up Milestones 
- [x] Set up Labels 
- [x] Associate with Project

**Comment by tb2459** [comment]
Labels have been chosen for the issues. Label "bug"  will be used to tell a collaborator that there is an issue present. The label "help wanted" is going to be used to ask for help from a collaborator. The label "invalid" will be used to indicate if an issue has been done incorrectly. The label "Progress" is used to indicate that there has been progress made for an issue. The label "Confusion" is used to indicate there is some miscommunication regarding a particular issue.

**Comment by Bkon243** [comment]
@ffund  Please review our project!

**Comment by ffund** [comment]
:+1:
